CREATE TABLE paciente (
    PatientID int NOT NULL PRIMARY KEY,
    ID NOT NULL VARCHAR(20),
    FirstName NOT NULL VARCHAR(255),
    LastName NOT NULL VARCHAR(255),
    Email NOT NULL VARCHAR(255),
    Phone NOT NULL VARCHAR(20)
)