version: '3.9'
services:
  api_hospital:
    container_name: api_hospital
    build: 
      context: .
      target: production
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db_hospital

  db_hospital:
    container_name: db_hospital
    image: postgres:15.1-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    user: postgres
    volumes:
      - db-hospital:/var/lib/postgresql/data

volumes:
  db-hospital:
