version: '3.9'
services:
  api_hospital:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    # depends_on:
    #   - db_hospital

  # db_hospital:
  #   image: postgres:15.1
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   env_file:
  #     - .env
#     volumes:
#       - db-hospital:/var/lib/postgresql/data

# volumes:
#   db-hospital: